### ISSUE TITLE
npm install fails - Mojave

### ISSUE THREAD

**Issue by Narayan-Gopalappa** [Timeular/noble-mac#31]
I have XCode installed but node-gyp build fails.

> xpc-connection@0.1.4 install /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/xpc-connection> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
VTL-FVFWV6K0HV2D:TestBLE narayan.gopalappa$ npm i

> xpc-connection@0.1.4 install /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/xpc-connection
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instan
ce

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instan
ce

Traceback (most recent call last):
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in Gene
rateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/bin/node" "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/xpc-connection
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:xpc-connection@0.1.4 xpc-connection@0.1.4 install: `node-gyp rebuild`
npm WARN install:xpc-connection@0.1.4 Exit status 1

> noble-mac@0.0.4 install /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac
> node install.js

> noble-mac@0.0.4 native_install /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for noble-mac@0.0.4 and node@6.0.0 (node-v48 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error zlib: zlib binding closed 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/bin/node" "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac/native/noble_mac.node" "--module_name=noble_mac" "--module_path=/Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac/native" "--node_abi_napi=node-v48"
gyp ERR! cwd /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/bin/node /Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac/native/noble_mac.node --module_name=noble_mac --module_path=/Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac/native --node_abi_napi=node-v48' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/bin/node" "/Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac
node-pre-gyp ERR! node -v v6.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/bin/node /Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac/native/noble_mac.node --module_name=noble_mac --module_path=/Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac/native --node_abi_napi=node-v48' (1)

npm ERR! Darwin 18.2.0
npm ERR! argv "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/bin/node" "/Users/narayan.gopalappa/.nvm/versions/node/v6.0.0/bin/npm" "run" "native_install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! noble-mac@0.0.4 native_install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noble-mac@0.0.4 native_install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the noble-mac package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs noble-mac
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls noble-mac
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE/node_modules/noble-mac/npm-debug.log
Test@1.0.0 /Users/narayan.gopalappa/Desktop/Me/Git/TestBLE
└─┬ noble-mac@0.0.4  (git+ssh://git@github.com/Timeular/noble-mac.git#e7bde3278691b3516b41b7c48fec1d66f6336c21)
  ├─┬ cross-spawn@6.0.5 
  │ ├── nice-try@1.0.5 
  │ ├── path-key@2.0.1 
  │ ├── semver@5.6.0 
  │ ├─┬ shebang-command@1.2.0 
  │ │ └── shebang-regex@1.0.0 
  │ └─┬ which@1.3.1 
  │   └── isexe@2.0.0 
  ├── napi-thread-safe-callback@0.0.6 
  ├── node-addon-api@1.6.2 
  └─┬ node-pre-gyp@0.10.3 
    ├── detect-libc@1.0.3 
    ├─┬ mkdirp@0.5.1 
    │ └── minimist@0.0.8 
    ├─┬ needle@2.2.4 
    │ ├─┬ iconv-lite@0.4.24 
    │ │ └── safer-buffer@2.1.2 
    │ └── sax@1.2.4 
    ├─┬ nopt@4.0.1 
    │ ├── abbrev@1.1.1 
    │ └─┬ osenv@0.1.5 
    │   ├── os-homedir@1.0.2 
    │   └── os-tmpdir@1.0.2 
    ├─┬ npm-packlist@1.4.1 
    │ ├─┬ ignore-walk@3.0.1 
    │ │ └─┬ minimatch@3.0.4 
    │ │   └─┬ brace-expansion@1.1.11 
    │ │     ├── balanced-match@1.0.0 
    │ │     └── concat-map@0.0.1 
    │ └── npm-bundled@1.0.6 
    ├─┬ npmlog@4.1.2 
    │ ├─┬ are-we-there-yet@1.1.5 
    │ │ ├── delegates@1.0.0 
    │ │ └─┬ readable-stream@2.3.6 
    │ │   ├── core-util-is@1.0.2 
    │ │   ├── isarray@1.0.0 
    │ │   ├── process-nextick-args@2.0.0 
    │ │   ├── string_decoder@1.1.1 
    │ │   └── util-deprecate@1.0.2 
    │ ├── console-control-strings@1.1.0 
    │ ├─┬ gauge@2.7.4 
    │ │ ├── aproba@1.2.0 
    │ │ ├── has-unicode@2.0.1 
    │ │ ├── object-assign@4.1.1 
    │ │ ├── signal-exit@3.0.2 
    │ │ ├─┬ string-width@1.0.2 
    │ │ │ ├── code-point-at@1.1.0 
    │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
    │ │ │   └── number-is-nan@1.0.1 
    │ │ ├─┬ strip-ansi@3.0.1 
    │ │ │ └── ansi-regex@2.1.1 
    │ │ └── wide-align@1.1.3 
    │ └── set-blocking@2.0.0 
    ├─┬ rc@1.2.8 
    │ ├── deep-extend@0.6.0 
    │ ├── ini@1.3.5 
    │ ├── minimist@1.2.0 
    │ └── strip-json-comments@2.0.1 
    ├─┬ rimraf@2.6.3 
    │ └─┬ glob@7.1.3 
    │   ├── fs.realpath@1.0.0 
    │   ├─┬ inflight@1.0.6 
    │   │ └── wrappy@1.0.2 
    │   ├── inherits@2.0.3 
    │   ├── once@1.4.0 
    │   └── path-is-absolute@1.0.1 
    └─┬ tar@4.4.8 
      ├── chownr@1.1.1 
      ├── fs-minipass@1.2.5 
      ├── minipass@2.3.5 
      ├── minizlib@1.2.1 
      ├── safe-buffer@5.1.2 
      └── yallist@3.0.3 

npm WARN optional Skipping failed optional dependency /noble/bluetooth-hci-socket:
npm WARN notsup Not compatible with your operating system or architecture: bluetooth-hci-socket@0.5.1
npm WARN Test@1.0.0 No repository field.
npm WARN Test@1.0.0 No license field.

**Comment by geovie** [comment]
@Narayan-Gopalappa This is not a `noble-mac` issue. Take a look at https://github.com/nodejs/node-gyp/issues/569 , thanks!
